del .\running_Dead\*.class
del .\running_Dead\actions\*.class
del .\running_Dead\actions\build\*.class
del .\running_Dead\actions\camera\*.class
del .\running_Dead\actions\equipables\*.class
del .\running_Dead\actions\interaction\*.class
del .\running_Dead\actions\movement\*.class
del .\running_Dead\networking\*.class
del .\running_Dead\server\*.class
